#!/bin/sh
set -e

case "$1" in
  remove | deconfigure)
    if [ -d /run/systemd/system ]; then
      systemctl stop proxy-scaler.service >/dev/null 2>&1 || true
      systemctl disable proxy-scaler.service >/dev/null 2>&1 || true
    fi
    ;;

  upgrade | failed-upgrade) ;;
esac

exit 0
